import React from 'react';

const breed = [
  '',
  'Afegão ou Afghan Hound',
  'Affenpinscher',
  'Airedale Terrier',
  'Akita Americano',
  'Akita Inu ou Akita Japonês',
  'Alano Espanhol',
  'American Staffordshire Terrier',
  'American Water Spaniel',
  'Barbet',
  'Basenji',
  'Basset Azul da Gasconha',
  'Basset Fulvo da Bretanha',
  'Basset Hound',
  'Beagle',
  'Beagle Harrier',
  'Bearded Collie',
  'Bedlington Terrier',
  'Bernese Mountain Dog',
  'Bichon Bolonhês',
  'Bichon Havanês',
  'Bichon Frisé',
  'Bichon Maltês',
  'Bloodhound',
  'Boiadeiro Australiano',
  'Boiadeiro Bernês',
  'Border Collie',
  'Border Terrier',
  'Borzoi',
  'Boston Terrier',
  'Boxer',
  'Bull Terrier',
  'Buldogue ou Bulldog Inglês',
  'Buldogue ou Bulldog Francês',
  'Bullmastiff ou Bulmastife',
  'Cairn Terrier',
  'Cane Corso',
  'Cão de Água Português',
  'Cão de Crista Chinês',
  'Cão de Montanha dos Pirinéus',
  'Cão lobo checoslovaco',
  'Cão da Groenlândia',
  'Caniche ou Poodle',
  'Cavalier King Charles Spaniel',
  'Chesapeake Bay Retriever',
  'Chihuahua',
  'Chow Chow',
  'Cirneco do Etna',
  'Cocker Spaniel Americano',
  'Cocker Spaniel Inglês',
  'Collie',
  'Coton de Tuléar',
  'Dachshund',
  'Dálmata',
  'Dandie Dinmont Terrier',
  'Doberman',
  'Dogue Alemão',
  'Dogue ou Dogo Argentino',
  'Dogue Canário',
  'Dogue de Bordeaux',
  'Elkhound Norueguês',
  'Fila Brasileiro',
  'Fox Terrier (Pêlo Duro e Pêlo Liso)',
  'Foxhound Inglês',
  'Galgo Escocês',
  'Galgo Irlandês',
  'Golden Retriever',
  'Gos d’Atura',
  'Grande Boiadeiro Suiço',
  'Greyhound ou Galgo Inglês',
  'Grifo da Bélgica',
  'Husky Siberiano',
  'Jack Russel Terrier',
  'King Charles',
  'Komondor',
  'Kuvasz',
  'Labradoodle',
  'Labrador Retriever',
  'Laika',
  'Lakeland Terrier',
  'Leonberger',
  'Lhasa Apso',
  'Malamute-do-Alasca',
  'Maltês',
  'Mastife',
  'Mastin dos Pirenéus',
  'Mastin do Tibete',
  'Mastin Espanhol',
  'Mastín Napolitano',
  'Norfolk Terrier',
  'Norwich Terrier',
  'Old English Sheepdog (Bobtail)',
  'Papillon',
  'Pastor Alemão',
  'Pastor Australiano',
  'Pastor Belga',
  'Pastor de Brie',
  'Pastor dos Pirenéus de Cara Rosa',
  'Pequeno Cão Leão',
  'Pequinês',
  'Perdigueiro',
  'Pinscher miniatura',
  'Pitbull',
  'Podengo',
  'Poodle',
  'Pointer',
  'Pug',
  'Rhodesian Ridgeback',
  'Rottweiler',
  'Rough Collie',
  'Sabueso (Espanhol ou Italiano)',
  'Saluki',
  'Samoieda',
  'São Bernardo',
  'Sem Raça Definida (SRD)',
  'Scottish Terrier',
  'Setter Irlandés',
  'Shar-Pei',
  'Shiba Inu',
  'Shih Tzu',
  'SilKy Terrier',
  'Skye Terrier',
  'Smooth Collie',
  'Spitz Alemão',
  'Spitz Lobo',
  'Spitz Gigante',
  'Spitz Médio',
  'Spitz Pequeno',
  'Spitz Anão',
  'Lulu da Pomerânia',
  'Staffordshire Bull Terrier',
  'Tamaskan',
  'Teckel',
  'Terra Nova',
  'Terrier Australiano',
  'Terrier Escocês',
  'Terrier Irlandês',
  'Terrier Japonês',
  'Terrier Negro Russo',
  'Terrier Norfolk',
  'Terrier Norwich',
  'Terrier Tibetano',
  'Tosa',
  'Weimaraner',
  'Welsh Corgi (Cardigan)',
  'Welsh Corgi (Pembroke)',
  'West Highland White Terrier',
  'Whippet',
  'Xoloitzcuintli',
  'Yorkshire Terrier',
  '',
];

export default breed;
